"""
InfraPulse Automated SMTP Email Dispatcher
==========================================

Handles HTML and plaintext email delivery with severity-tagged subject lines,
customizable NOC alert cards, and resilient fallback for development environments.
"""

import smtplib
import logging
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from typing import Optional, Dict, Any

from app.core.config import settings

logger = logging.getLogger("infrapulse.email")


def generate_alert_html(
    title: str,
    severity: str,
    target_name: str,
    metric_name: str,
    current_value: Optional[float],
    threshold_value: Optional[float],
    details: str,
    timestamp_str: str,
) -> str:
    """Renders a sleek NOC Dark-Mode HTML email template."""
    is_critical = severity.upper() == "CRITICAL"
    is_warning = severity.upper() == "WARNING"
    is_resolved = severity.upper() == "RESOLVED"

    badge_color = "#ef4444" if is_critical else "#f59e0b" if is_warning else "#10b981"
    bg_accent = "rgba(239, 68, 68, 0.1)" if is_critical else "rgba(245, 158, 11, 0.1)" if is_warning else "rgba(16, 185, 129, 0.1)"

    val_display = f"{current_value:.1f}%" if current_value is not None and "percent" in metric_name else f"{current_value}" if current_value is not None else "N/A"
    thresh_display = f"{threshold_value:.1f}%" if threshold_value is not None and "percent" in metric_name else f"{threshold_value}" if threshold_value is not None else "N/A"

    return f"""
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <style>
    body {{ font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background-color: #090d16; color: #e2e8f0; margin: 0; padding: 20px; }}
    .card {{ max-width: 600px; margin: 0 auto; background-color: #0f172a; border: 1px solid #1e293b; border-radius: 12px; overflow: hidden; box-shadow: 0 10px 25px rgba(0,0,0,0.5); }}
    .header {{ background-color: #090d16; padding: 18px 24px; border-bottom: 1px solid #1e293b; display: flex; align-items: center; justify-content: space-between; }}
    .logo {{ color: #06b6d4; font-family: monospace; font-size: 16px; font-weight: bold; letter-spacing: 1px; }}
    .content {{ padding: 24px; }}
    .badge {{ display: inline-block; padding: 4px 12px; border-radius: 9999px; font-size: 12px; font-weight: bold; font-family: monospace; text-transform: uppercase; background-color: {bg_accent}; color: {badge_color}; border: 1px solid {badge_color}; margin-bottom: 16px; }}
    .title {{ font-size: 18px; font-weight: 600; color: #ffffff; margin: 0 0 12px 0; }}
    .table {{ width: 100%; border-collapse: collapse; margin: 16px 0; font-size: 13px; font-family: monospace; }}
    .table td {{ padding: 8px 12px; border-bottom: 1px solid #1e293b; }}
    .table td.label {{ color: #94a3b8; width: 35%; }}
    .table td.val {{ color: #f1f5f9; font-weight: 600; }}
    .message-box {{ background-color: #131d35; border-left: 4px solid {badge_color}; padding: 12px 16px; border-radius: 4px; font-size: 13px; margin: 16px 0; color: #cbd5e1; }}
    .footer {{ background-color: #090d16; padding: 14px 24px; border-top: 1px solid #1e293b; font-size: 11px; color: #64748b; font-family: monospace; text-align: center; }}
  </style>
</head>
<body>
  <div class="card">
    <div class="header">
      <span class="logo">⚡ INFRAPULSE NOC</span>
    </div>
    <div class="content">
      <div class="badge">[{severity.upper()}]</div>
      <h2 class="title">{title}</h2>
      <div class="message-box">{details}</div>
      <table class="table">
        <tr><td class="label">Target Component:</td><td class="val">{target_name}</td></tr>
        <tr><td class="label">Metric Rule:</td><td class="val">{metric_name}</td></tr>
        <tr><td class="label">Observed Value:</td><td class="val" style="color: {badge_color};">{val_display}</td></tr>
        <tr><td class="label">Configured Threshold:</td><td class="val">{thresh_display}</td></tr>
        <tr><td class="label">Timestamp (UTC):</td><td class="val">{timestamp_str}</td></tr>
      </table>
    </div>
    <div class="footer">
      Automated alert generated by InfraPulse DCIM Telemetry Engine • Bangkok Edge DC
    </div>
  </div>
</body>
</html>
"""


def send_email_alert(
    subject: str,
    recipient_email: str,
    title: str,
    severity: str,
    target_name: str,
    metric_name: str,
    current_value: Optional[float],
    threshold_value: Optional[float],
    details: str,
    timestamp_str: str,
) -> bool:
    """
    Dispatches formatted HTML/Plaintext email alert to recipient.
    If SMTP credentials are not configured, logs alert clearly to stdout/logger.
    """
    to_email = recipient_email or settings.DEFAULT_ALERT_RECIPIENT
    html_content = generate_alert_html(
        title=title,
        severity=severity,
        target_name=target_name,
        metric_name=metric_name,
        current_value=current_value,
        threshold_value=threshold_value,
        details=details,
        timestamp_str=timestamp_str,
    )
    plain_content = f"[{severity.upper()}] {title}\n\nTarget: {target_name}\nMetric: {metric_name}\nValue: {current_value}\nThreshold: {threshold_value}\nDetails: {details}\nTime: {timestamp_str}"

    # Check if SMTP configuration is ready
    if not settings.SMTP_USER or not settings.SMTP_PASSWORD:
        logger.info(
            f"[EMAIL NOTIFICATION (SIMULATION)] To: {to_email} | Subject: {subject}\n"
            f"  Severity: {severity} | Target: {target_name} | {details}"
        )
        return True

    try:
        msg = MIMEMultipart("alternative")
        msg["Subject"] = subject
        msg["From"] = settings.SMTP_FROM_EMAIL or settings.SMTP_USER
        msg["To"] = to_email

        msg.attach(MIMEText(plain_content, "plain"))
        msg.attach(MIMEText(html_content, "html"))

        if settings.SMTP_PORT == 465:
            server = smtplib.SMTP_SSL(settings.SMTP_HOST, settings.SMTP_PORT, timeout=10.0)
        else:
            server = smtplib.SMTP(settings.SMTP_HOST, settings.SMTP_PORT, timeout=10.0)
            server.starttls()

        server.login(settings.SMTP_USER, settings.SMTP_PASSWORD)
        server.sendmail(msg["From"], [to_email], msg.as_string())
        server.quit()

        logger.info(f"Email alert successfully dispatched to '{to_email}': {subject}")
        return True
    except Exception as e:
        logger.error(f"Failed to deliver SMTP email alert to '{to_email}': {e}")
        return False
